name: "Setup Dependencies"
description: "Installs dependencies for the project"

inputs:
  install-all-dependencies:
    description: "Install development/testing dependencies"
    required: false
    default: "false"
  install-browsers:
    description: "Install browsers for testing"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install Python and UV
      uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
    - name: Set up Just
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
    - name: Install UV Dependencies
      if: ${{ inputs.install-all-dependencies == 'false' }}
      shell: bash
      run: just install
    - name: Install All UV Dependencies
      if: ${{ inputs.install-all-dependencies == 'true' }}
      shell: bash
      run: just install-all
    - name: Install Playwright Browsers
      if: ${{ inputs.install-browsers == 'true' }}
      shell: bash
      run: just playwright-install
