name: "Setup Dependencies"
description: "Installs dependencies for the project"

inputs:
  all-dependencies:
    description: "Install development/testing dependencies"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install Python and UV
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.2.2
      with:
        pyproject-file: "pyproject.toml"
        enable-cache: true
    - name: Set up Just
      uses: extractions/setup-just@v2
    - name: Install UV Dependencies
      if: ${{ inputs.all-dependencies == 'false' }}
      shell: bash
      run: just install
    - name: Install All UV Dependencies
      if: ${{ inputs.all-dependencies == 'true' }}
      shell: bash
      run: just install-all
